# Kafka topic configuration

topics:
  document-uploads:
    name: "dps.uploads"
    partitions: 12
    replication-factor: 3
    configs:
      cleanup.policy: delete
      retention.ms: 604800000  # 7 days
      max.message.bytes: 2097152  # 2MB
      compression.type: lz4

  document-processing:
    name: "dps.processing"
    partitions: 24
    replication-factor: 3
    configs:
      cleanup.policy: delete
      retention.ms: 259200000  # 3 days
      max.message.bytes: 1048576  # 1MB

  document-classification:
    name: "dps.classification"
    partitions: 8
    replication-factor: 3
    configs:
      cleanup.policy: delete
      retention.ms: 172800000  # 2 days

  document-events:
    name: "dps.events"
    partitions: 16
    replication-factor: 3
    configs:
      cleanup.policy: compact,delete
      retention.ms: 2592000000  # 30 days