  storage_usage:
    condition: "storage_usage_bytes / storage_capacity_bytes > 0.85"
    duration: "15m"
    labels:
      severity: warning
    annotations:
      summary: "High storage usage"
      description: "Storage usage exceeds 85% of capacity"

  memory_usage:
    condition: "process_resident_memory_bytes > 2e9"  # 2GB
    duration: "5m"
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Service memory usage exceeds 2GB"

  cpu_usage:
    condition: "rate(process_cpu_seconds_total[5m]) > 0.8"
    duration: "5m"
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage exceeds 80%"